-- StockPro Vogel - módulo Orçamentos
-- Patch estritamente aditivo e revisável.
-- Cria somente quotes, quote_items, quote_events, constraints e índices.
-- Não contém DROP, DELETE, dados, credenciais ou alterações destrutivas.
-- NÃO executar em Production sem autorização e revisão explícitas.

BEGIN;

CREATE TABLE quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  client_id UUID NOT NULL,
  opportunity_id UUID,
  created_by UUID NOT NULL,
  responsible_id UUID,
  status TEXT NOT NULL DEFAULT 'draft',
  valid_until DATE NOT NULL,
  payment_terms TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  discount_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  shipping_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  generated_order_id UUID UNIQUE,
  sent_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
  CONSTRAINT quotes_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES crm_opportunities(id) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT quotes_responsible_id_fkey FOREIGN KEY (responsible_id) REFERENCES profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT quotes_generated_order_id_fkey FOREIGN KEY (generated_order_id) REFERENCES orders(id) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT quotes_status_check CHECK (status IN ('draft', 'sent', 'approved', 'rejected', 'expired')),
  CONSTRAINT quotes_values_check CHECK (discount_value >= 0 AND shipping_value >= 0 AND subtotal >= 0 AND total_value >= 0)
);

CREATE TABLE quote_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL,
  item_type TEXT NOT NULL,
  product_id UUID,
  item_name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  quantity NUMERIC(12,2) NOT NULL,
  unit_price NUMERIC(14,2) NOT NULL,
  discount_value NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_value NUMERIC(14,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
  CONSTRAINT quote_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT quote_items_type_check CHECK (item_type IN ('product', 'equipment', 'custom')),
  CONSTRAINT quote_items_values_check CHECK (quantity > 0 AND unit_price >= 0 AND discount_value >= 0 AND total_value >= 0)
);

CREATE TABLE quote_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL,
  created_by UUID NOT NULL,
  type TEXT NOT NULL,
  description TEXT NOT NULL,
  previous_status TEXT,
  new_status TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT quote_events_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE RESTRICT ON UPDATE NO ACTION,
  CONSTRAINT quote_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX quotes_client_id_idx ON quotes(client_id);
CREATE INDEX quotes_opportunity_id_idx ON quotes(opportunity_id);
CREATE INDEX quotes_created_by_idx ON quotes(created_by);
CREATE INDEX quotes_responsible_id_idx ON quotes(responsible_id);
CREATE INDEX quotes_status_idx ON quotes(status);
CREATE INDEX quotes_created_at_idx ON quotes(created_at);
CREATE INDEX quote_items_quote_id_idx ON quote_items(quote_id);
CREATE INDEX quote_items_product_id_idx ON quote_items(product_id);
CREATE INDEX quote_events_quote_id_created_at_idx ON quote_events(quote_id, created_at);
CREATE INDEX quote_events_created_by_idx ON quote_events(created_by);

COMMIT;
