-- StockPro Vogel - schema completo atualizado
create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('administrador','gerente','vendedor','funcionario','tecnico','representante');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.account_status as enum ('pending','approved','rejected','inactive');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  role public.app_role not null default 'representante',
  status public.account_status not null default 'pending',
  name text not null default '',
  document text not null default '',
  phone text not null default '',
  cep text not null default '',
  city text not null default '',
  street text not null default '',
  number text not null default '',
  no_number boolean not null default false,
  neighborhood text not null default '',
  access_code text,
  seller_code text,
  manager_code text,
  responsible_seller_id uuid references public.profiles(id),
  responsible_manager_id uuid references public.profiles(id),
  created_by uuid references public.profiles(id),
  permissions jsonb not null default '{}'::jsonb,
  approval_notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.profiles add column if not exists access_code text;
alter table public.profiles add column if not exists seller_code text;
alter table public.profiles add column if not exists manager_code text;
alter table public.profiles add column if not exists responsible_seller_id uuid references public.profiles(id);
alter table public.profiles add column if not exists responsible_manager_id uuid references public.profiles(id);
alter table public.profiles add column if not exists created_by uuid references public.profiles(id);
alter table public.profiles add column if not exists permissions jsonb not null default '{}'::jsonb;
alter table public.profiles add column if not exists approval_notes text;
alter table public.profiles add column if not exists updated_at timestamp with time zone default now();

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  document text not null default '',
  phone text not null default '',
  email text not null default '',
  cep text not null default '',
  city text not null default '',
  street text not null default '',
  number text not null default '',
  no_number boolean not null default false,
  neighborhood text not null default '',
  products text[] default '{}',
  created_at timestamp with time zone default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sku text not null default '',
  category text not null default '',
  subcategory text not null default '',
  cost_price numeric not null default 0,
  sale_price numeric not null default 0,
  quantity integer not null default 0,
  min_stock integer not null default 0,
  supplier_id uuid references public.suppliers(id),
  description text not null default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.products add column if not exists subcategory text not null default '';
create unique index if not exists products_sku_unique on public.products(sku) where sku <> '';

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  document text not null default '',
  phone text not null default '',
  cep text not null default '',
  city text not null default '',
  street text not null default '',
  number text not null default '',
  no_number boolean not null default false,
  neighborhood text not null default '',
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  created_by uuid references public.profiles(id),
  client_id uuid references public.clients(id),
  status text not null default 'pendente',
  item_type text not null default '',
  item_id uuid,
  equipment_name text not null default '',
  quantity integer not null default 1,
  total_value numeric not null default 0,
  shipping_value numeric not null default 0,
  tracking_code text not null default '',
  tracking_location text not null default '',
  conta_azul_status text not null default '',
  notes text not null default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.orders add column if not exists equipment_name text not null default '';
alter table public.orders add column if not exists conta_azul_status text not null default '';

create table if not exists public.movements (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  item_type text not null,
  item_id uuid,
  quantity integer not null default 0,
  notes text not null default '',
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default now()
);

create table if not exists public.components (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default '',
  equipment text not null default '',
  supplier_id uuid references public.suppliers(id),
  quantity integer not null default 0,
  min_stock integer not null default 0,
  created_at timestamp with time zone default now()
);

alter table public.components add column if not exists equipment text not null default '';
alter table public.components add column if not exists supplier_id uuid references public.suppliers(id);
alter table public.components add column if not exists quantity integer not null default 0;
alter table public.components add column if not exists min_stock integer not null default 0;
alter table public.components add column if not exists category text not null default '';

create table if not exists public.assemblies (
  id uuid primary key default gen_random_uuid(),
  equipment text not null,
  quantity integer not null default 1,
  technician_id uuid references public.profiles(id),
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default now()
);

create table if not exists public.conta_azul_logs (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id),
  status text not null default '',
  message text not null default '',
  created_at timestamp with time zone default now()
);

-- Produtos padrão de revenda
insert into public.products (name, sku, category, subcategory, cost_price, sale_price, quantity, min_stock, description)
values
('Lâmpada LED dimerizável E27', 'REV-LAMP-E27', 'Lâmpadas dimerizáveis', 'E27', 0, 0, 0, 0, 'Produto padrão de revenda'),
('Lâmpada LED dimerizável PAR20', 'REV-LAMP-PAR20', 'Lâmpadas dimerizáveis', 'PAR20', 0, 0, 0, 0, 'Produto padrão de revenda'),
('Dimmer rotativo', 'REV-DIM-ROT', 'Dimmer', 'Dimmer rotativo', 0, 0, 0, 0, 'Produto padrão de revenda'),
('Dimmer Wi-Fi', 'REV-DIM-WIFI', 'Dimmer', 'Dimmer Wi-Fi', 0, 0, 0, 0, 'Produto padrão de revenda'),
('Soquete E-27 porcelana', 'REV-SOQ-E27-POR', 'Soquetes E-27', 'Porcelana', 0, 0, 0, 0, 'Produto padrão de revenda')
on conflict (sku) do nothing;

-- Para facilitar o desenvolvimento, RLS fica desativado. Ative depois em produção com políticas completas.
alter table public.profiles disable row level security;
alter table public.suppliers disable row level security;
alter table public.products disable row level security;
alter table public.clients disable row level security;
alter table public.orders disable row level security;
alter table public.movements disable row level security;
alter table public.movements add column if not exists order_id uuid references public.orders(id);
alter table public.components disable row level security;
alter table public.assemblies disable row level security;
alter table public.conta_azul_logs disable row level security;

notify pgrst, 'reload schema';

-- Patch adicional 2026-06 - pedidos, NF, edição/exclusão, fornecedores e assemblies
alter table public.suppliers add column if not exists invoice_number text not null default '';
alter table public.suppliers add column if not exists federal_invoice_number text not null default '';
alter table public.suppliers add column if not exists updated_at timestamp with time zone default now();

alter table public.clients add column if not exists updated_at timestamp with time zone default now();

alter table public.orders add column if not exists order_number bigint generated by default as identity;
alter table public.orders add column if not exists item_kind text not null default 'produto';
alter table public.orders add column if not exists item_type text not null default 'produto';
alter table public.orders add column if not exists item_id uuid;
alter table public.orders add column if not exists equipment_name text not null default '';
alter table public.orders add column if not exists quantity integer not null default 1;
alter table public.orders add column if not exists total_value numeric not null default 0;
alter table public.orders add column if not exists shipping_value numeric not null default 0;
alter table public.orders add column if not exists tracking_code text not null default '';
alter table public.orders add column if not exists tracking_location text not null default '';
alter table public.orders add column if not exists notes text not null default '';
alter table public.orders add column if not exists invoice_status text not null default 'not_issued';
alter table public.orders add column if not exists invoice_number text not null default '';
alter table public.orders add column if not exists invoice_url text not null default '';
alter table public.orders add column if not exists invoice_provider text not null default '';
alter table public.orders add column if not exists updated_at timestamp with time zone default now();

alter table public.components add column if not exists equipment text not null default '';
alter table public.components add column if not exists supplier_id uuid references public.suppliers(id);
alter table public.components add column if not exists quantity integer not null default 0;
alter table public.components add column if not exists min_stock integer not null default 0;
alter table public.components add column if not exists category text not null default '';

alter table public.assemblies add column if not exists equipment text not null default '';
alter table public.assemblies add column if not exists quantity integer not null default 1;
alter table public.assemblies add column if not exists technician_id uuid references public.profiles(id);
alter table public.assemblies add column if not exists created_by uuid references public.profiles(id);

create table if not exists public.fiscal_entries (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid references public.suppliers(id),
  invoice_number text not null default '',
  federal_invoice_number text not null default '',
  item_id uuid,
  quantity integer not null default 0,
  unit_cost numeric not null default 0,
  total_cost numeric not null default 0,
  notes text not null default '',
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.fiscal_entries disable row level security;
notify pgrst, 'reload schema';

-- Ajustes para baixa automática de componentes por equipamento
alter table public.components alter column quantity type numeric using quantity::numeric;
alter table public.components alter column min_stock type numeric using min_stock::numeric;
alter table public.movements alter column quantity type numeric using quantity::numeric;
alter table public.components add column if not exists cost_price numeric not null default 0;
alter table public.components add column if not exists nf_number text not null default '';
alter table public.components add column if not exists receita_federal_nf text not null default '';
alter table public.components add column if not exists updated_at timestamp with time zone default now();

notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');

-- Ajustes 2026-07 - montagem, componentes selecionáveis e usuário técnico
alter table public.assemblies add column if not exists equipment_name text not null default '';
alter table public.assemblies add column if not exists product_name text not null default '';
alter table public.assemblies add column if not exists name text not null default '';
alter table public.components add column if not exists cost_price numeric not null default 0;
alter table public.components add column if not exists nf_number text not null default '';
alter table public.components add column if not exists receita_federal_nf text not null default '';
alter table public.components add column if not exists updated_at timestamp with time zone default now();
notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');
