"use client";

import { useState } from "react";

type FormState = { codigo:string; nome:string; email:string; senha:string; document:string; phone:string; cep:string; city:string; street:string; number:string; no_number:boolean; neighborhood:string; };
const empty: FormState = { codigo:"", nome:"", email:"", senha:"", document:"", phone:"", cep:"", city:"", street:"", number:"", no_number:false, neighborhood:"" };
function onlyNumbers(value: string) { return String(value || "").replace(/\D/g, ""); }
function maskCpfCnpj(value: string) { const n=onlyNumbers(value).slice(0,14); if(n.length<=11) return n.replace(/^(\d{3})(\d)/,"$1.$2").replace(/^(\d{3})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1-$2"); return n.replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2"); }
function maskPhone(value: string) { const n=onlyNumbers(value).slice(0,11); if(n.length<=10) return n.replace(/^(\d{2})(\d)/,"($1) $2").replace(/(\d{4})(\d)/,"$1-$2"); return n.replace(/^(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d)/,"$1-$2"); }
function maskCep(value: string) { return onlyNumbers(value).slice(0,8).replace(/^(\d{5})(\d)/,"$1-$2"); }

export default function CriarAdminPage() {
  const [form,setForm]=useState<FormState>(empty); const [loading,setLoading]=useState(false); const [msg,setMsg]=useState("");
  function set(campo:keyof FormState, valor:string|boolean){ setForm(a=>({...a,[campo]:valor})); }
  async function buscarCepPorValor(valorCep:string){ const cep=onlyNumbers(valorCep); if(cep.length!==8) return; try{ const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`); const d=await r.json(); if(d.erro){setMsg("CEP não encontrado."); return;} setForm(a=>({...a,cep:maskCep(cep),city:d.localidade||"",street:d.logradouro||"",neighborhood:d.bairro||""})); }catch{ setMsg("Erro ao buscar CEP. Verifique sua internet."); } }
  async function criarAdmin(){ setLoading(true); setMsg(""); const payload={...form,document:onlyNumbers(form.document),phone:onlyNumbers(form.phone),cep:onlyNumbers(form.cep),number:form.no_number?"":form.number}; try{ const res=await fetch('/api/admin/criar-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data=await res.json(); if(!res.ok){setMsg(data.error||'Erro ao criar administrador.'); return;} setMsg('Administrador criado com sucesso. Agora você pode fazer login.'); setForm(empty); }catch{setMsg('Erro inesperado ao criar administrador.');} finally{setLoading(false);} }
  return <main style={{minHeight:'100vh',background:'#020617',color:'white',padding:'40px'}}><section className="card"><h1 style={{fontSize:34,margin:'0 0 8px',fontWeight:900}}>Criar administrador</h1><p style={{color:'#94a3b8',marginBottom:30}}>Use esta tela apenas para criar o primeiro administrador do sistema.</p><div className="form-grid"><Campo label="Código secreto" value={form.codigo} onChange={v=>set('codigo',v)}/><Campo label="Nome completo" value={form.nome} onChange={v=>set('nome',v)}/><Campo label="E-mail" type="email" value={form.email} onChange={v=>set('email',v)}/><Campo label="Senha" type="password" value={form.senha} onChange={v=>set('senha',v)}/><Campo label="CPF ou CNPJ" value={form.document} onChange={v=>set('document',maskCpfCnpj(v))}/><Campo label="Telefone" value={form.phone} onChange={v=>set('phone',maskPhone(v))}/><Campo label="CEP" value={form.cep} onChange={v=>{const c=maskCep(v); set('cep',c); if(onlyNumbers(c).length===8) buscarCepPorValor(c);}} onBlur={()=>buscarCepPorValor(form.cep)}/><Campo label="Cidade" value={form.city} onChange={v=>set('city',v)}/><Campo label="Rua" value={form.street} onChange={v=>set('street',v)}/><div className="field"><label>Número</label><input className="input" value={form.number} disabled={form.no_number} onChange={e=>set('number',e.target.value)}/><button type="button" className={form.no_number?'btn btn-blue':'btn btn-gray'} style={{marginTop:10,minHeight:38,padding:'8px 14px'}} onClick={()=>{const n=!form.no_number; set('no_number',n); if(n) set('number','')}}>{form.no_number?'Sem número marcado':'Sem número'}</button></div><Campo label="Bairro" value={form.neighborhood} onChange={v=>set('neighborhood',v)}/></div><div className="form-actions"><button className="btn btn-blue" onClick={criarAdmin} disabled={loading}>{loading?'Criando...':'Criar administrador'}</button><button className="btn btn-gray" onClick={()=>{window.location.href='/login'}}>Ir para login</button></div>{msg&&<div style={{marginTop:26,padding:16,borderRadius:16,background:'#020617',color:msg.includes('sucesso')?'#4ade80':'#f87171',fontWeight:800,border:'1px solid rgba(148,163,184,.25)'}}>{msg}</div>}</section></main>;
}
function Campo({label,value,onChange,type='text',onBlur}:{label:string;value:string;type?:string;onChange:(v:string)=>void;onBlur?:()=>void}){return <div className="field"><label>{label}</label><input className="input" type={type} value={value} onBlur={onBlur} onChange={e=>onChange(e.target.value)}/></div>}
